# Site configuration

title: Pour Frank
timezone: Europe/Paris

url: https://sudweb.github.io/frank/
locale: fr_FR

## SEO
robots: index,follow

collections:
  testimonies:
    output: false

plugins:
  - jekyll-optional-front-matter
  - jekyll-microtypo
